// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RepositoryLayer.ApplicationDatabase;

namespace RepositoryLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CommanLayer.Models.Comparision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOnCreation");

                    b.Property<string>("Result");

                    b.Property<double>("Value_One");

                    b.Property<string>("Value_One_Unit")
                        .IsRequired();

                    b.Property<double>("Value_Two");

                    b.Property<string>("Value_Two_Unit")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Comparisions");
                });

            modelBuilder.Entity("CommanLayer.Models.Quantity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOnCreation");

                    b.Property<string>("OptionType")
                        .IsRequired();

                    b.Property<double>("Result");

                    b.Property<double>("Value");

                    b.HasKey("Id");

                    b.ToTable("Quantities");
                });
#pragma warning restore 612, 618
        }
    }
}
